import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ReactNode } from "react";
import {CombinedProvider} from "@/providers";
import Header from "@/components/Header";
import DarkModeToggle from "@/components/DarkModeToogle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <CombinedProvider>
          <Header />
          <div>
            <DarkModeToggle/>
          </div>
          {children}
        </CombinedProvider>
      </body>
    </html>
  );
};
export default RootLayout;